config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/dashboard'
  get 'pages/create'
  root 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

    validates :title, presence: true
    validates :image, presence: true
    validates :content, presence: true
    validate :contenido_without_spoilers
    default_scope {where ("LENGTH(content) > 1")}
    scope :ordered_by_date, -> { order(created_at: :desc) }


    def contenido_without_spoilers
        if content.include?("spoiler") == true
            content.gsub! 'spoiler', ' '
            
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only:
:dashboard


  def index
    @posts = Post.ordered_by_date
  end

  def dashboard
  end

  def create
    @post = Post.create(title: params[:title], image: params[:img_url], content: params[:content])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">
  <a class="navbar-brand" href="#">Posts</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%= pages_index_path %>">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=pages_dashboard_path %>">Dashboard</a>
      </li>
      
    </ul>
  </div>
  </div>
</nav>


   <div class="container mt-4">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/create.html.erb
<% if @post.errors.any? %>
<div id="error_explanation">
<h2>
<%= pluralize(@post.errors.count, "error") %>
Prohibido crear este post por:
</h2>
<ul>
<% @post.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% else %>
<h1>Has creado un post con exito</h1>
<% end %>

app/views/pages/dashboard.html.erb
<h1>Creacion de formularios</h1>

<form id="create_posts" action="/pages/create" method="get">
    <div class="form-group">
        <label for="titulo">Titulo </label>
        <input name="title" class="form-control" >
    </div>
        <label for="imagen">Imagen </label>
        <input name="img_url" class="form-control" >
    <div class="form-group mt-3">
        <label for="content">Contenido</label>
        <textarea name="content" class="form-control" cols="20" rows="3"></textarea>
     </div>   

        <button type="submit" value="Enviar" class="btn btn-primary btn-lg">Enviar</button>
    

</form>

app/views/pages/index.html.erb
<h1>Posts</h1>


<table class="table mt-5">
    <tr>
    <th> Titulo del Post</th>
    <th>Imagen del Post</th>
    <th>Contenido del post</th>
    <th>Fecha de Creacion</th>
    </tr>

    <% @posts.each do |post|%>
    <tr>
        <td><%=post.title%></td> 
        <td><%=post.image%></td> 
        <td><%=post.content%></td> 
        <td><%=post.created_at%></td>
    </tr>
    <% end%>

</table>